In [1]:
#pip install pandas openpyxl
import sys
!{sys.executable} -m pip install openpyxl
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

Requirement already satisfied: openpyxl in c:\users\russe\anaconda3\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\russe\anaconda3\lib\site-packages (from openpyxl) (1.1.0)

In [2]:
import os
print(os.listdir('data'))

['2018 Accident Incident Report.xlsx', '2019 Accident Report.xlsx', '2020 Accident Report.xlsx', '2021 Accident Report.xlsx', 'accidents_2024.csv', 'accidents_2025.csv', 'accidents_2025_preventable_addition.csv', 'grayline_fleet_vehicles.csv']

In [3]:
accidents2018_df = pd.read_excel('data/2018 Accident Incident Report.xlsx', sheet_name = 'Sheet1',skiprows=2, engine='openpyxl')
accidents2019_df = pd.read_excel('data/2019 Accident Report.xlsx',sheet_name = 'DRIVER FAULT',skiprows=1, engine='openpyxl')
accidents2020_df = pd.read_excel('data/2020 Accident Report.xlsx', sheet_name = 'Master', engine='openpyxl')
accidents2021_df = pd.read_excel('data/2021 Accident Report.xlsx', sheet_name = 'Master', engine='openpyxl')
accidents2024_df = pd.read_csv('data/accidents_2024.csv')
accidents2025_df = pd.read_csv('data/accidents_2025.csv')
accidents2025prevent_df = pd.read_csv('data/accidents_2025_preventable_addition.csv')
graylinefleet_df = pd.read_csv('data/grayline_fleet_vehicles.csv')

In [4]:
accidents2018_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 131 entries, 0 to 130
Data columns (total 22 columns):
 #   Column                                           Non-Null Count  Dtype
---  ------                                           --------------  -----
 0   Claim #                                          128 non-null    object
 1   Employee Name                                    128 non-null    object
 2   Dept.                                            116 non-null    object
 3   Date Occurred                                    127 non-null    object
 4   Incident / Accident                              126 non-null    object
 5   DOT Recordable?                                  126 non-null    object
 6   Unit No.                                         120 non-null    object
 7   Description                                      123 non-null    object
 8   GL Driver                                        69 non-null     object
 9   NON GL Driver                                    33 non-null     object
 10  GL Employee                                      118 non-null    object
 11  NON GL Employee                                  114 non-null    object
 12  Ins. Notified                                    111 non-null    object
 13  In-House, Protective, or Other Driver/Insuance   100 non-null    object
 14  Jerry's $ GL Bus Repair                          11 non-null     object
 15  Quote                                            3 non-null      object
 16  Cost for other vehicle repair                    9 non-null      object
 17  Actual                                           1 non-null      object
 18  Police Report                                    65 non-null     object
 19  Drive Cam?                                       54 non-null     object
 20  Safety Committee Ruling                          62 non-null     object
 21  Status                                           67 non-null     object
dtypes: object(22)
memory usage: 22.6+ KB

In [5]:
acc2018renamed_df = accidents2018_df.rename(columns = {'Claim #':'ClaimNo', 'Employee Name':'DriverName', 'Dept.':'Department', 'Date Occurred ':'AccidentDate', \
                                                      'Incident / Accident' : 'IncidentAccident', 'Unit No.' : 'UnitNo.' , \
                                                      'Description' : 'Description' , 'GL Driver':'GLDriver' ,'NON GL Driver ':'NonGLDriver', 'GL Employee':'GLEmployee', \
                                                      'Ins. Notified':'InsNotified', 'In-House, Protective, or Other Driver/Insuance ': 'ClaimType' , \
                                                       "Jerry's $ GL Bus Repair ": 'JerrysGLBusRepair', \
                                                       'Quote':'Quote', 'Actual':'Actual', 'Cost for other vehicle repair':'CostForOtherVehicleRepair', 'Police Report':'PoliceReport', \
                                                      'Drive Cam?':'Drivecam', 'Safety Committee Ruling':'SafetyCommitteeRuling','DOT Recordable?':'DOTRecordable', \
                                                      'Date Occured':'AccidentDate', 'Status':'ClaimStatus'})

In [6]:
accidents2018_df.columns

Index(['Claim #', 'Employee Name', 'Dept.', 'Date Occurred ',
       'Incident / Accident', 'DOT Recordable?', 'Unit No.', 'Description',
       'GL Driver', 'NON GL Driver ', 'GL Employee', 'NON GL Employee',
       'Ins. Notified', 'In-House, Protective, or Other Driver/Insuance ',
       'Jerry's $ GL Bus Repair ', 'Quote', 'Cost for other vehicle repair',
       'Actual', 'Police Report', 'Drive Cam?', 'Safety Committee Ruling',
       'Status'],
      dtype='object')

In [7]:
acc2018renamed_df.head()

,ClaimNo,DriverName,Department,AccidentDate,IncidentAccident,DOTRecordable,UnitNo.,Description,GLDriver,NonGLDriver,...,InsNotified,ClaimType,JerrysGLBusRepair,Quote,CostForOtherVehicleRepair,Actual,PoliceReport,Drivecam,SafetyCommitteeRuling,ClaimStatus
0,010318-533,Brittney Patterson,School Bus,2018-01-04 00:00:00,Incident,Non-DOT,533,"Driver hit a sign, no damage reported",X,NaN,...,N,In-House,NaN,NaN,NaN,NaN,N,N,Preventable,Closed
1,010718-1015,Scott Wangrud,Charter,2018-01-07 00:00:00,Incident,Non-DOT,1015,Supposedly hit an Anchor Bus' mirror,X,NaN,...,N,NaN,NaN,NaN,NaN,NaN,NaN,N,Preventable,Closed
2,011518-1021,Thomas House,Charter,2018-01-15 00:00:00,Accident,Non-DOT,1021,Driver hit a sign,X,NaN,...,N,In-House,3185.35,NaN,NaN,NaN,N,N,Preventable,Closed
3,011618-1015,David Armstrong,Charter,2018-01-16 00:00:00,Accident,Non-DOT,1015,Bus slid into concrete light pole. Parking lot...,NaN,X,...,N,In-House,NaN,NaN,NaN,NaN,N,N,Non-Preventable,Closed
4,011918-232,William Moncrief,Tour,2018-01-19 00:00:00,Accident,Non-DOT,232,Our bus was hit by Freeman Trucking. Right sid...,NaN,X,...,N,OP Ins,NaN,NaN,NaN,NaN,Y,N,Non-Preventable,Open

In [8]:
accidents2019_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 159 entries, 0 to 158
Data columns (total 30 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Claim #                  158 non-null    object
 1   Other Claim #            27 non-null     object
 2   Driver                   158 non-null    object
 3   Dept.                    154 non-null    object
 4   Unit #                   154 non-null    object
 5   Date                     154 non-null    datetime64[ns]
 6   Description              154 non-null    object
 7   GL Driver                154 non-null    object
 8   NON GL Driver            154 non-null    object
 9   GL Employee              154 non-null    object
 10  NON GL Employee          154 non-null    object
 11  Ins Notified?            154 non-null    object
 12  In-House/Ins             154 non-null    object
 13  GL Repair Cost           145 non-null    object
 14  3rd Party Cost           34 non-null     float64
 15  Ins Fees                 153 non-null    float64
 16  Time                     153 non-null    object
 17  Location                 153 non-null    object
 18  Weather                  154 non-null    object
 19  Lighting                 153 non-null    object
 20  Road Surface             154 non-null    object
 21  Road Type                153 non-null    object
 22  Control Device           55 non-null     object
 23  Driver Experience        153 non-null    object
 24  Raduis                   152 non-null    object
 25  Police Report            153 non-null    object
 26  DOT Recordable?          153 non-null    object
 27  Drive Cam?               153 non-null    object
 28  Safety Committee Ruling  153 non-null    object
 29  Status                   154 non-null    object
dtypes: datetime64[ns](1), float64(2), object(27)
memory usage: 37.4+ KB

In [28]:
acc2019renamed_df = accidents2019_df.rename(columns = {'Claim #':'ClaimNo', 'Other Claim #':'OtherClaimNo', 'Driver':'DriverName', \
                                                      'Dept.':'Department', 'Unit #':'UnitNo', 'Date':'AccidentDate', 'Description':'Description', \
                                                      'GL Driver':'GLDriver', 'NON GL Driver ':'NonGLDriver', 'Ins Notified?':'InsNotified', \
                                                      'In-House/Ins':'InHouse/Ins', 'GL Repair Cost':'GLRepairCost', '3rd Party Cost':'3rdPartyCost',\
                                                      'INS Fees':'InsFees', 'Time':'Time', 'Location':'Location', 'Weather':'Weather', 'Lighting':'Lighting', \
                                                      'Road Surface':'RoadSurface', 'Road Type':'RoadType', 'Control Device':'ControlDevice', \
                                                      'Driver Experience':'DriverExperience', 'Radius':'Radius', 'Police Report':'PoliceReport', \
                                                      'DOT Recordable?':'DOTRecordable', 'Drive Cam?':'DriveCam', 'Safety Committee Ruling':'SafetyCommitteeRuling', \
                                                      'Status':'ClaimStatus', 'GL Employee':'GLEmployee'})

In [13]:
acc2019renamed_df.columns

Index(['ClaimNo', 'OtherClaimNo', 'DriverName', 'Department', 'UnitNo',
       'AccidentDate', 'Description', 'GLDriver', 'NON GL Driver ',
       'GLEmployee', 'NonGLDriver', 'InsNotified', 'In-House/Ins ',
       'GL Repair Cost ', '3rdPartyCost', 'Ins Fees', 'Time', 'Location',
       'Weather', 'Lighting', 'RoadSurface', 'RoadType', 'ControlDevice',
       'DriverExperience', 'Raduis', 'PoliceReport', 'DOTRecordable',
       'DriveCam', 'SafetyCommRuling', 'ClaimStatus'],
      dtype='object')

In [29]:
acc2019renamed_df.head()

,ClaimNo,OtherClaimNo,DriverName,Department,UnitNo,AccidentDate,Description,GLDriver,NonGLDriver,GLEmployee,...,RoadSurface,RoadType,ControlDevice,DriverExperience,Raduis,PoliceReport,DOTRecordable,DriveCam,SafetyCommitteeRuling,ClaimStatus
0,010719-003,NaN,Jerry Mischler,Shop,7,2019-01-07,GL Mechanic hit another vehicle in an intersec...,Y,N,N,...,Dry,Straight,Traffic Light,N,0-50,Y,Y,N,N,Open
1,011719-616,NaN,Rawand Koyee,SB,616,2019-01-17,Backed into 565 front passenger window,Y,N,N,...,N,N,N,3-4 Years,N,N,N,N,N,N
2,011719-1021,NaN,Shawn Yokley,C,1021,2019-01-17,hooked back bumper on a cement pole,Y,N,N,...,N,N,N,6-11 MThs,N,N,N,N,N,N
3,012019-727,NaN,James Johnson,BC,4727,2019-01-20,Hit pole in garage on right side,Y,N,N,...,N,N,N,1-2 Yrs,N,N,N,N,N,N
4,012719-1023,NaN,Sadie Demoss,SS,1023,2019-01-27,driver backed 1023 into 243 mirror,Y,N,N,...,N,N,N,5+ Yrs,N,N,N,N,N,N

In [ ]:
accidents2020_df.info()

In [15]:
acc2020renamed_df = accidents2020_df.rename(columns = {'CLAIM NUMBER' : 'ClaimNo', 'CLAIM NUMBER2' : 'ClaimNo2', 'DRIVER NAME' : 'DriverName',\
                                                      'EMPLOYEE ID' : 'EmployeeId',  'DEPARTMENT' : 'Department', 'ACC DATE': 'AccidentDate', \
                                                      'DESCRIPTION' : 'description', 'DRIVER INJURED' : 'driverinjured', 'OP INJURED' : 'opinjured', \
                                                      'CLAIM TYPE' : 'ClaimType', 'GL BUS ESTIMATE' : 'GLBusEstimate', 'GL BUS REPAIR' : 'GLBusRepair', \
                                                      'OP REPAIR COST' : 'OpRepairCost', 'INS FEE' : 'InsFee', 'OP INS PAID TO GL' : 'OpInsPaidToGL', \
                                                      'INSURANCE DEDUCTIBLE' : 'InsDeductable', 'TOTAL' : 'Total', 'Time' : 'Time', 'LOCATION' : 'Location', \
                                                      'WEATHER' : 'Weather', 'LIGHTING' : 'Lighting', 'ROAD SURFACE' : 'RoadSurface', 'ROAD TYPE' : 'RoadType', \
                                                      'DRIVER ACTION' : 'DriverAction','DRIVER EXPERIENCE' : 'DriverExperience', 'RADIUS' : 'Radius', 'POLICE REPORT' : 'PoliceReport', \
                                                      'DOT RECORDABLE' : 'DOTRecordable', 'VIDEO' : 'Video', 'PREVENTABLE?' : 'Preventable', \
                                                      'STATUS' : 'ClaimStatus', 'UNIT NO' : 'UnitNo'})

In [30]:
acc2020renamed_df.head()

,ClaimNo,ClaimNo2,DriverName,EmployeeId,Department,UnitNo,AccidentDate,description,driverinjured,opinjured,...,RoadSurface,RoadType,DriverAction,DriverExperience,Radius,PoliceReport,DOTRecordable,Video,Preventable,ClaimStatus
0,010620-246,0,Alesha Harney,11038,Charter,246,2020-01-06,car hit the front bumper of the bus - scuffed ...,False,False,...,Dry,Parking Lot,Stop Sign,7.0,0-50,False,False,False,False,CLOSED
1,010820-214,0,Kelly Westerlund,10979,Sightseeing,214,2020-01-08,"driver hit a service truck turning right, bus ...",False,False,...,Dry,Residential Street,turning right,1.0,0-50,True,False,False,True,CLOSED
2,010920-1019,767903,Robert Kimbrell,10346,Charter,1019,2020-01-09,driver clipped a college student when she drov...,False,False,...,Dry,Residential Street,N,30.0,0-50,True,False,False,True,CLOSED
3,010920-1019,0,Robert Kimbrell,10346,Charter,1019,2020-01-09,driver failed to set brake and bus rolled into...,False,False,...,Dry,Parking Lot,stopped,30.0,0-50,False,False,True,True,CLOSED
4,011020-721,767935,Michael Beattie,10039,RTA,721,2020-01-10,hit OP right rear fender turning left at Charl...,False,False,...,Dry,Intersection,turning left,33.0,0-50,True,False,False,True,CLOSED

In [ ]:
accidents2021_df.info()

In [17]:
acc2021renamed_df = accidents2021_df.rename(columns = {'ClaimNo' : 'Claimno', 'InsClaimNo' : 'InsClaimNo', 'DRIVERNAME' : 'DriverName','EmployeeID' : 'EmployeeId', \
                                                      'DEPT' : 'Department', 'UnitNo' : 'UnitNo', 'AccidentDate' : 'AccidentDate', 'DESCRIPTION' : 'Description', \
                                                      'OPFAULT' : 'OpFault', 'INJURY' : 'Injury', 'GL Estimate':'GLBusEstimate', 'Final':'Final', 'OPRepair':'OpRepair',\
                                                      'Total':'total', 'TIME':'time', 'LOCATION':'location', 'CityState':'citystate', 'WEATHER':'weather', \
                                                      'LIGHTING':'Lighting', 'RoadSurface':'RoadSurface', 'RoadType':'RoadType', 'DriverAction':'DriverAction', \
                                                      'PoliceReport':'PoliceReport', 'DOTRecordable?' : 'DOTRecordable', 'VIDEO': 'Video', 'PREV':'Preventable', \
                                                      'Date Occured': 'AccidentDate',  'ClaimType' : 'ClaimType','STATUS' : 'ClaimStatus', 'ClaimAdj':'ClaimAdj',\
                                                      'NOTES':'Notes', 'VMS Accident No':'VMSAccidentNo'})

In [19]:
acc2021renamed_df.head(5)

,Claimno,InsClaimNo,DriverName,EmployeeId,Department,UnitNo,AccidentDate,Description,OpFault,Injury,...,RoadType,DriverAction,PoliceReport,DOTRecordable,Video,Preventable,ClaimStatus,ClaimAdj,Notes,VMSAccidentNo
0,011321-715,110.0,Elizabeth Burton,10086.0,RTA,715,2021-01-13,Penske truck hit passenger side mirror of bus ...,1.0,False,...,Residential Street,"Stopped, Not Moving",FALSE,FALSE,False,False,Open,NaN,Unscheduled activity id78458,110.0
1,011421-280,111.0,Robert Schneider,11016.0,RTA,280,2021-01-14,a bobcat truck pulling a 36' to 40' constructi...,1.0,False,...,Residential Street,"Stopped, Not Moving",FALSE,FALSE,False,False,Open,NaN,UnscheduledActivity id 78478,111.0
2,011721-329,112.0,Anthony Wells,10914.0,Charter,329,2021-01-17,"driver backed into a pay booth, rear screen o...",0.0,False,...,Parking Lot,Right Turn,FALSE,FALSE,False,True,Open,NaN,driver submitted defect with description that ...,112.0
3,011721-4101,768974.0,Sameh Shaker,10566.0,School Bus,4101,2021-01-17,Our bus was parked on the side of the road whe...,1.0,TRUE,...,Downtown,"Stopped, Not Moving",TRUE,TRUE,False,False,Open,Lisa Carey,State Farm Claim No. 4215V715T - reported to L...,113.0
4,011921-000,235957.0,Jenniefer Stephens,10597.0,Charter,0,2021-01-19,IW was closing tire cover when the bumper clos...,0.0,TRUE,...,Parking Lot,"Stopped, Not Moving",False,False,False,True,Open,Tracy Robinson,Work Comp,NaN

In [ ]:
accidents2024_df.info()

In [31]:
accidents2024_df.columns

Index(['claimno', 'insclaimno', 'drivername', 'employeeid', 'dept', 'unitno',
       'accidentdate', 'description', 'preventable?', 'injury',
       'loss_of_bonus_', 'coaching', 'final___jerrys_estimate', 'est',
       'oprepair', 'total', 'time', 'address', 'citystate', 'weather',
       'lighting', 'roadsurface', 'roadtype', 'driveraction', 'policereport',
       'dotrecordable', 'video', 'prev', 'status', 'claimadj', 'notes',
       'vms_accident_no'],
      dtype='object')

In [18]:
acc2024renamed_df = accidents2024_df.rename(columns = {'dept' : 'Department', 'unitno' : 'UnitNo', 'preventable?':'Preventable', \
                                                      'loss_of_bonus_':'LossOfBonus', 'final__jerrys_estimate':'FinalJerrysEstimate', \
                                                      'dotrecordable?' : 'DOTRecordable', 'prev':'Preventable', 'status' : 'ClaimStatus', \
                                                      'vms_accident_no':'VMSAccidentNo'})

In [25]:
acc2024renamed_df.head()

,claimno,insclaimno,drivername,employeeid,Department,UnitNo,accidentdate,description,Preventable,injury,...,roadtype,driveraction,policereport,dotrecordable,video,Preventable,Claimstatus,claimadj,notes,VMSAccidentno
0,010124-311,Not Registered,Douglas Bumpus,5,Charter,311,2024-01-01 00:00:00.000,Turning in parking lot of Buccees hit a car.,yes,no,...,Parking Lot,Turning Left,Yes,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered
1,010524-319,Not Registered,Devon Whitmore,0-1,Charter,319,2024-01-05 00:00:00.000,"Backing bus into slot,fatigue driving back got...",yes,no,...,Lebanon Pike or Shop Parking Lot,Backing,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered
2,011124-312,Not Registered,Troy Fontechia,1-2,Charter,312,2024-01-11 00:00:00.000,Car nearly crashed pick up truck while merging...,no,No,...,Interstate/Highway,Driving Forward,Yes,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered
3,Not Registered,Not Registered,DERRICK Lowe,Not Registered,RTA,722,2024-01-18 00:00:00.000,Thursday is my day to get my Bus wash when i...,yes,Not Registered,...,Dickerson pik shop,Driving Forward,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Marker light,Not Registered
4,012524-336,Not Registered,Estus Owens,5,Charter,336,2024-01-25 00:00:00.000,I was backing up at the Embassy suites downtow...,yes,no,...,Parking Lot,Backing,No,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered

In [ ]:
accidents2025_df.info()

In [24]:
accidents2025_df.columns

Index(['claimno', 'insclaimno', 'drivername', 'employeeid', 'dept', 'unitno',
       'accidentdate', 'description', 'preventable?', 'injury',
       'loss_of_bonus_', 'coaching', 'final___jerrys_estimate', 'est',
       'oprepair', 'total', 'time', 'address', 'citystate', 'weather',
       'lighting', 'roadsurface', 'roadtype', 'driveraction', 'policereport',
       'dotrecordable', 'video', 'prev', 'status', 'claimadj', 'notes',
       'vms_accident_no'],
      dtype='object')

In [34]:
acc2025renamed_df = accidents2025_df.rename(columns = {'claimno' : 'ClaimNo',  'insclaimno' : 'InsClaimNo', 'DRIVERNAME' :'drivername','employeeid' : 'EmployeeId', \
                                                     'dept' : 'Department','unitno' : 'UnitNo', 'accidentdate' : 'AccidentDate', 'description': 'Description', \
                                                       'preventable?': 'preventable', 'injury': 'Injury', 'GL Estimate':'GLBusEstimate', 'Final':'Final', 'OPRepair':'OpRepair',\
                                                      'Total':'total', 'TIME':'time', 'LOCATION':'location', 'CityState':'citystate', 'WEATHER':'weather', \
                                                      'LIGHTING':'Lighting', 'RoadSurface':'RoadSurface', 'RoadType':'RoadType', 'DriverAction':'DriverAction', \
                                                      'PoliceReport':'PoliceReport', 'DOTRecordable?' : 'DOTRecordable', 'VIDEO': 'Video', 'PREV':'Preventable', \
                                                      'Date Occured': 'AccidentDate',  'ClaimType' : 'ClaimType','STATUS' : 'ClaimStatus', 'ClaimAdj':'ClaimAdj',\
                                                      'NOTES':'Notes', 'VMS Accident No':'VMSAccidentNo'})

In [35]:
acc2025renamed_df.head()

,ClaimNo,InsClaimNo,drivername,EmployeeId,Department,UnitNo,AccidentDate,Description,preventable?,injury,...,roadtype,driveraction,policereport,dotrecordable,video,prev,status,claimadj,notes,vms_accident_no
0,Not Registered,Not Registered,Tashelia Murphy,Not Registered,School Bus,593,2025-01-08 00:00:00.000,I was stopped at the red light in a bit of tra...,no,No,...,Intersection,"Stopped, Not Moving",Yes,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered
1,011825-331,Not Registered,Alesha Harney,Not Registered,Charter,331,2025-01-18 00:00:00.000,Cut to close to concrete barrier getting turne...,yes,No,...,Residential or City Street,Backing,No,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered
2,012325-715,773848,Kimberly Perkins,Not Registered,RTA,715,2025-01-23 00:00:00.000,I was making a left turn on to Enterprise driv...,yes,Not Registered,...,Intersection,Turning Left,Yes,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered
3,012525-249,Not Registered,Dale Jaco,Not Registered,Charter,249,2025-01-25 00:00:00.000,I was parked on 21st Ave and a mini bus from ...,no,No,...,Residential or City Street,"Stopped, Not Moving",No,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered
4,012925-338,Not Registered,Lonnie McGee,Not Registered,Charter,338,2025-01-29 00:00:00.000,Murphy Athletic Center MTSU\n2650 Middle Tenne...,Yes,No,...,Parking Lot (NOT Gray Line TN),Backing,No,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered

In [ ]:
accidents2025prevent_df.info()

In [21]:
acc2025prevrenamed_df = accidents2025_df.rename(columns = {'dept':'Department', 'unitno':'UnitNo', 'preventable?':'Preventable', \
                                                      'loss_of_bonus_':'LossOfBonus', 'final__jerrys_estimate':'FinalJerrysEstimate', \
                                                      'dotrecordable?':'DOTRecordable', 'prev':'preventable', 'status':'claimstatus', \
                                                      'VMS_Accident_No':'VMSaccidentno'})

In [22]:
acc2025prevrenamed_df.head()

,claimno,insclaimno,drivername,employeeid,Department,UnitNo,accidentdate,description,Preventable,injury,...,roadtype,driveraction,policereport,dotrecordable,video,preventable,claimstatus,claimadj,notes,vms_accident_no
0,Not Registered,Not Registered,Tashelia Murphy,Not Registered,School Bus,593,2025-01-08 00:00:00.000,I was stopped at the red light in a bit of tra...,no,No,...,Intersection,"Stopped, Not Moving",Yes,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered
1,011825-331,Not Registered,Alesha Harney,Not Registered,Charter,331,2025-01-18 00:00:00.000,Cut to close to concrete barrier getting turne...,yes,No,...,Residential or City Street,Backing,No,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered
2,012325-715,773848,Kimberly Perkins,Not Registered,RTA,715,2025-01-23 00:00:00.000,I was making a left turn on to Enterprise driv...,yes,Not Registered,...,Intersection,Turning Left,Yes,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered
3,012525-249,Not Registered,Dale Jaco,Not Registered,Charter,249,2025-01-25 00:00:00.000,I was parked on 21st Ave and a mini bus from ...,no,No,...,Residential or City Street,"Stopped, Not Moving",No,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered
4,012925-338,Not Registered,Lonnie McGee,Not Registered,Charter,338,2025-01-29 00:00:00.000,Murphy Athletic Center MTSU\n2650 Middle Tenne...,Yes,No,...,Parking Lot (NOT Gray Line TN),Backing,No,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered

In [ ]:
graylinefleet_df.info()